<?php

namespace Database\Seeders\Tenants;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Basic Tee',
                'tenant_id' => 1,
                'slug' => 'basic-tee',
                'color' => 'Black',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 45,
                'stock' => 150,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Basic Tee White',
                'tenant_id' => 1,
                'slug' => 'basic-tee-white',
                'color' => 'Aspen White',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-02.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 45,
                'stock' => 150,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Basic Tee Charcoal',
                'tenant_id' => 1,
                'slug' => 'basic-tee-charcoal',
                'color' => 'Charcoal',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-03.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 45,
                'stock' => 150,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Artwork Tee',
                'tenant_id' => 1,
                'slug' => 'artwork-tee',
                'color' => 'Iso Dots',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-04.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 45,
                'stock' => 150,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nomad Pouch',
                'tenant_id' => 1,
                'slug' => 'nomad-pouch',
                'color' => 'White and Black',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-01.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 50,
                'stock' => 150,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zip Tote Basket',
                'tenant_id' => 1,
                'slug' => 'zip-tote-basket',
                'color' => 'Washed Black',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-02.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 140,
                'stock' => 150,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medium Stuff Satchel',
                'tenant_id' => 1,
                'slug' => 'medium-stuff-satchel',
                'color' => 'Blue',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-03.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 220,
                'stock' => 150,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'High Wall Tote',
                'tenant_id' => 1,
                'slug' => 'high-wall-tote',
                'color' => 'Black and Orange',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-04.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 210,
                'stock' => 150,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zip Tote Basket',
                'tenant_id' => 1,
                'slug' => 'zip-tote-basket',
                'color' => 'White and black',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-05.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 140,
                'stock' => 150,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zip High Wall Tote',
                'tenant_id' => 1,
                'slug' => 'zip-high-wall-tote',
                'color' => 'White and blue',
                'image_path' => 'https://tailwindui.com/img/ecommerce-images/category-page-07-product-06.jpg',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 160,
                'stock' => 150,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chunky Knit Beanie',
                'tenant_id' => 1,
                'slug' => 'chunky-knit-beanie',
                'color' => 'Charcoal',
                'image_path' => 'https://cdn.shopify.com/s/files/1/0167/4484/products/beanie-charcoal-2_400x.jpg?v=1562024308',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 35,
                'stock' => 4,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Men\'s Essential Tee',
                'tenant_id' => 1,
                'slug' => 'mens-essential-tee',
                'color' => 'black',
                'image_path' => 'https://cdn.shopify.com/s/files/1/0167/4484/products/essential-model-81_400x.jpg?v=1560367417',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 22,
                'stock' => 4,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Smell the Roses',
                'tenant_id' => 1,
                'slug' => 'smell-the-roses',
                'color' => 'black',
                'image_path' => 'https://cdn.shopify.com/s/files/1/0167/4484/products/roses-black-2_400x.jpg?v=1624384584',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 32,
                'stock' => 4,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Men\'s Essential Tee',
                'tenant_id' => 1,
                'slug' => 'mens-essential-tee-2',
                'color' => 'Brown',
                'image_path' => 'https://cdn.shopify.com/s/files/1/0167/4484/products/canyon-1_8860cf50-4d94-4462-82e6-0aca6c2da608_400x.jpg?v=1596036665',
                'description' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur vitae modi sunt voluptate vel earum totam eius impedit accusamus, fugiat at fuga ducimus ipsa, eos tenetur, veritatis obcaecati officia blanditiis.',
                'price' => 40,
                'stock' => 4,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
